import { createTool } from '@mastra/core/tools';
import { z } from 'zod';

export const blackRockTopPerformingFundsTool = createTool({
  id: 'black-rock-top-performing-funds',
  description: 'Get BlackRock top performing funds data including fixed income and variable income with performance metrics',
  inputSchema: z.object({
    includeFixedIncome: z.boolean().optional().describe('Include fixed income data (default: true)'),
    includeVariableIncome: z.boolean().optional().describe('Include variable income data (default: true)'),
  }),
  outputSchema: z.object({
    fixedIncome: z.array(z.object({
      instrument: z.string(),
      price: z.number(),
      previousPrice: z.number(),
      variation: z.number(),
      variationPercentage: z.number(),
      time: z.string(),
      yieldYTDAnnualized: z.number(),
      yieldMonthlyAnnualized: z.number(),
      yieldWeeklyAnnualized: z.number(),
      yieldYTD: z.number(),
      yieldWeekly: z.number(),
      yieldAnnual: z.number(),
      yieldMonthly: z.number(),
      minPrice12Months: z.number(),
      maxPrice12Months: z.number(),
      fundType: z.literal('Renta Fija'),
    })),
    variableIncome: z.array(z.object({
      instrument: z.string(),
      price: z.number(),
      previousPrice: z.number(),
      variation: z.number(),
      variationPercentage: z.number(),
      time: z.string(),
      yieldYTDAnnualized: z.number(),
      yieldMonthlyAnnualized: z.number(),
      yieldWeeklyAnnualized: z.number(),
      yieldYTD: z.number(),
      yieldWeekly: z.number(),
      yieldAnnual: z.number(),
      yieldMonthly: z.number(),
      minPrice12Months: z.number(),
      maxPrice12Months: z.number(),
      fundType: z.literal('Renta Variable'),
    })),
  }),
  execute: async ({ context }) => {
    return await getFixedIncomeData(context.includeFixedIncome, context.includeVariableIncome);
  },
});

const getFixedIncomeData = async (includeFixedIncome = true, includeVariableIncome = true) => {
  // Mock data for Fixed Income (Renta Fija)
  const fixedIncomeData = [
    {
      instrument: "BLKCP1A",
      price: 1.88,
      previousPrice: 1.87,
      variation: 0.01,
      variationPercentage: 0.4021,
      time: "08:52:00",
      yieldYTDAnnualized: 24.74,
      yieldMonthlyAnnualized: 31.46,
      yieldWeeklyAnnualized: 29.38,
      yieldYTD: 15.60,
      yieldWeekly: 0.50,
      yieldAnnual: 12.86,
      yieldMonthly: 2.30,
      minPrice12Months: 1.8836,
      maxPrice12Months: 1.8836,
      fundType: "Renta Fija" as const,
    },
    {
      instrument: "BLKGUB3A",
      price: 92.79,
      previousPrice: 92.14,
      variation: 0.65,
      variationPercentage: 0.7052,
      time: "08:52:00",
      yieldYTDAnnualized: 20.78,
      yieldMonthlyAnnualized: 33.30,
      yieldWeeklyAnnualized: 42.26,
      yieldYTD: 13.17,
      yieldWeekly: 0.68,
      yieldAnnual: 12.86,
      yieldMonthly: 2.42,
      minPrice12Months: 92.7908,
      maxPrice12Months: 92.7908,
      fundType: "Renta Fija" as const,
    },
    {
      instrument: "BLKUDI+A",
      price: 38.58,
      previousPrice: 38.47,
      variation: 0.10,
      variationPercentage: 0.2725,
      time: "08:52:00",
      yieldYTDAnnualized: 19.42,
      yieldMonthlyAnnualized: 21.85,
      yieldWeeklyAnnualized: 27.57,
      yieldYTD: 12.34,
      yieldWeekly: 0.47,
      yieldAnnual: 11.64,
      yieldMonthly: 1.66,
      minPrice12Months: 38.5833,
      maxPrice12Months: 38.5833,
      fundType: "Renta Fija" as const,
    },
    {
      instrument: "BLKPZOA",
      price: 5.29,
      previousPrice: 5.27,
      variation: 0.02,
      variationPercentage: 0.3606,
      time: "08:52:00",
      yieldYTDAnnualized: 14.43,
      yieldMonthlyAnnualized: 19.42,
      yieldWeeklyAnnualized: 23.48,
      yieldYTD: 9.23,
      yieldWeekly: 0.41,
      yieldAnnual: 11.37,
      yieldMonthly: 1.49,
      minPrice12Months: 5.2975,
      maxPrice12Months: 5.2975,
      fundType: "Renta Fija" as const,
    },
    {
      instrument: "GOLD1+A",
      price: 242.63,
      previousPrice: 242.41,
      variation: 0.22,
      variationPercentage: 0.09,
      time: "08:52:00",
      yieldYTDAnnualized: 10.24,
      yieldMonthlyAnnualized: 10.17,
      yieldWeeklyAnnualized: 10.19,
      yieldYTD: 6.60,
      yieldWeekly: 0.18,
      yieldAnnual: 10.39,
      yieldMonthly: 0.81,
      minPrice12Months: 242.6318,
      maxPrice12Months: 242.6318,
      fundType: "Renta Fija" as const,
    }
  ];

  // Mock data for Variable Income (Renta Variable)
  const variableIncomeData = [
    {
      instrument: "BLKNUM1A",
      price: 388.07,
      previousPrice: 387.93,
      variation: 0.14,
      variationPercentage: 0.0366,
      time: "08:52:00",
      yieldYTDAnnualized: -5.61,
      yieldMonthlyAnnualized: 1636.86,
      yieldWeeklyAnnualized: -0.67,
      yieldYTD: -3.71,
      yieldWeekly: -0.01,
      yieldAnnual: -4.12,
      yieldMonthly: 26.85,
      minPrice12Months: 388.0788,
      maxPrice12Months: 388.0788,
      fundType: "Renta Variable" as const,
    },
    {
      instrument: "BLKCREA",
      price: 1.76,
      previousPrice: 1.75,
      variation: 0.02,
      variationPercentage: 0.8644,
      time: "08:52:00",
      yieldYTDAnnualized: 30.29,
      yieldMonthlyAnnualized: 76.79,
      yieldWeeklyAnnualized: 135.04,
      yieldYTD: 18.94,
      yieldWeekly: 1.67,
      yieldAnnual: 11.46,
      yieldMonthly: 4.86,
      minPrice12Months: 1.7655,
      maxPrice12Months: 1.7655,
      fundType: "Renta Variable" as const,
    },
    {
      instrument: "BLKMEDA",
      price: 3.79,
      previousPrice: 3.77,
      variation: 0.02,
      variationPercentage: 0.4749,
      time: "08:52:00",
      yieldYTDAnnualized: 39.98,
      yieldMonthlyAnnualized: 51.50,
      yieldWeeklyAnnualized: 89.04,
      yieldYTD: 24.67,
      yieldWeekly: 1.24,
      yieldAnnual: 28.39,
      yieldMonthly: 3.52,
      minPrice12Months: 3.7958,
      maxPrice12Months: 3.7958,
      fundType: "Renta Variable" as const,
    },
    {
      instrument: "BLKFUSAA",
      price: 2.74,
      previousPrice: 2.72,
      variation: 0.02,
      variationPercentage: 0.8148,
      time: "08:52:00",
      yieldYTDAnnualized: 9.91,
      yieldMonthlyAnnualized: 39.41,
      yieldWeeklyAnnualized: -42.41,
      yieldYTD: 6.39,
      yieldWeekly: -1.06,
      yieldAnnual: 20.57,
      yieldMonthly: 2.80,
      minPrice12Months: 2.743,
      maxPrice12Months: 2.743,
      fundType: "Renta Variable" as const,
    },
    {
      instrument: "GOLD5+A",
      price: 783.48,
      previousPrice: 777.92,
      variation: 5.56,
      variationPercentage: 0.7148,
      time: "08:52:00",
      yieldYTDAnnualized: 10.85,
      yieldMonthlyAnnualized: 29.40,
      yieldWeeklyAnnualized: 15.53,
      yieldYTD: 6.99,
      yieldWeekly: 0.28,
      yieldAnnual: 12.47,
      yieldMonthly: 2.17,
      minPrice12Months: 783.4888,
      maxPrice12Months: 783.4888,
      fundType: "Renta Variable" as const,
    },
    {
      instrument: "BLK3+A",
      price: 5.66,
      previousPrice: 5.64,
      variation: 0.02,
      variationPercentage: 0.3867,
      time: "08:52:00",
      yieldYTDAnnualized: 10.60,
      yieldMonthlyAnnualized: 20.85,
      yieldWeeklyAnnualized: 15.00,
      yieldYTD: 6.82,
      yieldWeekly: 0.27,
      yieldAnnual: 11.20,
      yieldMonthly: 1.59,
      minPrice12Months: 5.6655,
      maxPrice12Months: 5.6655,
      fundType: "Renta Variable" as const,
    }
  ];

  return {
    fixedIncome: includeFixedIncome ? fixedIncomeData : [],
    variableIncome: includeVariableIncome ? variableIncomeData : [],
  };
};
