import { createTool } from '@mastra/core/tools';
import { z } from 'zod';

export const tradeHistoryTool = createTool({
  id: 'get-trade-history',
  description: 'Get historical trading transactions for portfolio analysis',
  inputSchema: z.object({
    portfolioId: z.string().optional().describe('Optional portfolio identifier'),
    startDate: z.string().optional().describe('Optional start date for filtering (YYYY-MM-DD)'),
    endDate: z.string().optional().describe('Optional end date for filtering (YYYY-MM-DD)'),
  }),
  outputSchema: z.object({
    data: z.array(z.object({
      folio: z.number(),
      symbol: z.string(),
      series: z.string(),
      orderType: z.string(),
      shares: z.number(),
      canceledShares: z.number(),
      price: z.number(),
      total: z.number(),
      sharesAssigned: z.number(),
      status: z.string(),
      orderDate: z.string(),
      expirationDate: z.string(),
      orderTime: z.string(),
      marketType: z.string(),
    })),
    summary: z.object({
      totalTrades: z.number(),
      totalBuyValue: z.number(),
      totalSellValue: z.number(),
      totalCommission: z.number(),
      netCashFlow: z.number(),
    }),
  }),
  execute: async ({ context }) => {
    return await getTradeHistory(context.portfolioId, context.startDate, context.endDate);
  },
});

const getTradeHistory = async (portfolioId?: string, startDate?: string, endDate?: string) => {
  // For now, return realistic dummy data that aligns with portfolio holdings
  // In the future, this would fetch real trade history from an API
  
  // Default to LT (Long Term) if no portfolioId specified
  const id = portfolioId || 'LT';
  
  if (id === 'DT') {
    // Day Trading trade history data
    const trades = [
      {
          "folio": 200001,
          "symbol": "TSLA",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 1.0,
          "canceledShares": 0.0,
          "price": 8281.67,
          "total": 8281.67,
          "sharesAssigned": 1.0,
          "status": "Asignada",
          "orderDate": "17/10/2024",
          "expirationDate": "17/10/2024",
          "orderTime": "09:30:15",
          "marketType": "SIC"
      },
      {
          "folio": 200002,
          "symbol": "TSLA",
          "series": "*",
          "orderType": "VENTA",
          "shares": 1.0,
          "canceledShares": 0.0,
          "price": 8420.50,
          "total": 8420.50,
          "sharesAssigned": 1.0,
          "status": "Asignada",
          "orderDate": "17/10/2024",
          "expirationDate": "17/10/2024",
          "orderTime": "14:25:30",
          "marketType": "SIC"
      },
      {
          "folio": 200003,
          "symbol": "AAPL",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 2.0,
          "canceledShares": 0.0,
          "price": 4410.80,
          "total": 8821.60,
          "sharesAssigned": 2.0,
          "status": "Asignada",
          "orderDate": "18/10/2024",
          "expirationDate": "18/10/2024",
          "orderTime": "10:15:45",
          "marketType": "SIC"
      },
      {
          "folio": 200004,
          "symbol": "AAPL",
          "series": "*",
          "orderType": "VENTA",
          "shares": 2.0,
          "canceledShares": 0.0,
          "price": 4395.25,
          "total": 8790.50,
          "sharesAssigned": 2.0,
          "status": "Asignada",
          "orderDate": "18/10/2024",
          "expirationDate": "18/10/2024",
          "orderTime": "15:45:20",
          "marketType": "SIC"
      },
      {
          "folio": 200005,
          "symbol": "WALMEX",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 250.0,
          "canceledShares": 0.0,
          "price": 58.99,
          "total": 14747.50,
          "sharesAssigned": 250.0,
          "status": "Asignada",
          "orderDate": "21/10/2024",
          "expirationDate": "21/10/2024",
          "orderTime": "09:45:15",
          "marketType": "MC"
      },
      {
          "folio": 200006,
          "symbol": "WALMEX",
          "series": "*",
          "orderType": "VENTA",
          "shares": 100.0,
          "canceledShares": 0.0,
          "price": 59.85,
          "total": 5985.00,
          "sharesAssigned": 100.0,
          "status": "Asignada",
          "orderDate": "21/10/2024",
          "expirationDate": "21/10/2024",
          "orderTime": "13:20:40",
          "marketType": "MC"
      },
      {
          "folio": 200007,
          "symbol": "CEMEXCPO",
          "series": "CPO",
          "orderType": "COMPRA",
          "shares": 800.0,
          "canceledShares": 0.0,
          "price": 11.81,
          "total": 9448.00,
          "sharesAssigned": 800.0,
          "status": "Asignada",
          "orderDate": "22/10/2024",
          "expirationDate": "22/10/2024",
          "orderTime": "10:30:25",
          "marketType": "MC"
      },
      {
          "folio": 200008,
          "symbol": "CEMEXCPO",
          "series": "CPO",
          "orderType": "VENTA",
          "shares": 200.0,
          "canceledShares": 0.0,
          "price": 12.15,
          "total": 2430.00,
          "sharesAssigned": 200.0,
          "status": "Asignada",
          "orderDate": "22/10/2024",
          "expirationDate": "22/10/2024",
          "orderTime": "15:10:35",
          "marketType": "MC"
      },
      {
          "folio": 200009,
          "symbol": "AMXB",
          "series": "B",
          "orderType": "COMPRA",
          "shares": 600.0,
          "canceledShares": 0.0,
          "price": 15.31,
          "total": 9186.00,
          "sharesAssigned": 600.0,
          "status": "Asignada",
          "orderDate": "24/10/2024",
          "expirationDate": "24/10/2024",
          "orderTime": "09:20:15",
          "marketType": "MC"
      },
      {
          "folio": 200010,
          "symbol": "AMXB",
          "series": "B",
          "orderType": "VENTA",
          "shares": 200.0,
          "canceledShares": 0.0,
          "price": 15.65,
          "total": 3130.00,
          "sharesAssigned": 200.0,
          "status": "Asignada",
          "orderDate": "24/10/2024",
          "expirationDate": "24/10/2024",
          "orderTime": "11:45:50",
          "marketType": "MC"
      },
      {
          "folio": 200011,
          "symbol": "GAPB",
          "series": "B",
          "orderType": "COMPRA",
          "shares": 40.0,
          "canceledShares": 0.0,
          "price": 344.32,
          "total": 13772.80,
          "sharesAssigned": 40.0,
          "status": "Asignada",
          "orderDate": "25/10/2024",
          "expirationDate": "25/10/2024",
          "orderTime": "10:15:30",
          "marketType": "MC"
      },
      {
          "folio": 200012,
          "symbol": "GAPB",
          "series": "B",
          "orderType": "VENTA",
          "shares": 40.0,
          "canceledShares": 0.0,
          "price": 340.85,
          "total": 13634.00,
          "sharesAssigned": 40.0,
          "status": "Asignada",
          "orderDate": "25/10/2024",
          "expirationDate": "25/10/2024",
          "orderTime": "14:30:45",
          "marketType": "MC"
      },
      {
          "folio": 200013,
          "symbol": "MSFT",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 1.0,
          "canceledShares": 0.0,
          "price": 8281.67,
          "total": 8281.67,
          "sharesAssigned": 1.0,
          "status": "Asignada",
          "orderDate": "28/10/2024",
          "expirationDate": "28/10/2024",
          "orderTime": "09:35:20",
          "marketType": "SIC"
      },
      {
          "folio": 200014,
          "symbol": "MSFT",
          "series": "*",
          "orderType": "VENTA",
          "shares": 1.0,
          "canceledShares": 0.0,
          "price": 8385.40,
          "total": 8385.40,
          "sharesAssigned": 1.0,
          "status": "Asignada",
          "orderDate": "28/10/2024",
          "expirationDate": "28/10/2024",
          "orderTime": "12:20:15",
          "marketType": "SIC"
      },
      {
          "folio": 200015,
          "symbol": "BIMBOA",
          "series": "A",
          "orderType": "COMPRA",
          "shares": 180.0,
          "canceledShares": 0.0,
          "price": 65.09,
          "total": 11716.20,
          "sharesAssigned": 180.0,
          "status": "Asignada",
          "orderDate": "29/10/2024",
          "expirationDate": "29/10/2024",
          "orderTime": "10:45:35",
          "marketType": "MC"
      },
      {
          "folio": 200016,
          "symbol": "BIMBOA",
          "series": "A",
          "orderType": "VENTA",
          "shares": 180.0,
          "canceledShares": 0.0,
          "price": 64.75,
          "total": 11655.00,
          "sharesAssigned": 180.0,
          "status": "Asignada",
          "orderDate": "29/10/2024",
          "expirationDate": "29/10/2024",
          "orderTime": "15:25:40",
          "marketType": "MC"
      },
      {
          "folio": 200017,
          "symbol": "FEMSAUBD",
          "series": "UBD",
          "orderType": "COMPRA",
          "shares": 70.0,
          "canceledShares": 0.0,
          "price": 193.97,
          "total": 13577.90,
          "sharesAssigned": 70.0,
          "status": "Asignada",
          "orderDate": "01/11/2024",
          "expirationDate": "01/11/2024",
          "orderTime": "09:25:15",
          "marketType": "MC"
      },
      {
          "folio": 200018,
          "symbol": "FEMSAUBD",
          "series": "UBD",
          "orderType": "VENTA",
          "shares": 70.0,
          "canceledShares": 0.0,
          "price": 191.50,
          "total": 13405.00,
          "sharesAssigned": 70.0,
          "status": "Asignada",
          "orderDate": "01/11/2024",
          "expirationDate": "01/11/2024",
          "orderTime": "13:40:25",
          "marketType": "MC"
      },
      {
          "folio": 200019,
          "symbol": "NVDA",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 3.0,
          "canceledShares": 0.0,
          "price": 2450.80,
          "total": 7352.40,
          "sharesAssigned": 3.0,
          "status": "Asignada",
          "orderDate": "04/11/2024",
          "expirationDate": "04/11/2024",
          "orderTime": "10:15:30",
          "marketType": "SIC"
      },
      {
          "folio": 200020,
          "symbol": "NVDA",
          "series": "*",
          "orderType": "VENTA",
          "shares": 3.0,
          "canceledShares": 0.0,
          "price": 2520.15,
          "total": 7560.45,
          "sharesAssigned": 3.0,
          "status": "Asignada",
          "orderDate": "04/11/2024",
          "expirationDate": "04/11/2024",
          "orderTime": "14:50:45",
          "marketType": "SIC"
      },
      {
          "folio": 200021,
          "symbol": "GFNORTEO",
          "series": "O",
          "orderType": "COMPRA",
          "shares": 90.0,
          "canceledShares": 0.0,
          "price": 144.83,
          "total": 13034.70,
          "sharesAssigned": 90.0,
          "status": "Asignada",
          "orderDate": "05/11/2024",
          "expirationDate": "05/11/2024",
          "orderTime": "09:30:20",
          "marketType": "MC"
      },
      {
          "folio": 200022,
          "symbol": "GFNORTEO",
          "series": "O",
          "orderType": "VENTA",
          "shares": 90.0,
          "canceledShares": 0.0,
          "price": 147.65,
          "total": 13288.50,
          "sharesAssigned": 90.0,
          "status": "Asignada",
          "orderDate": "05/11/2024",
          "expirationDate": "05/11/2024",
          "orderTime": "11:45:35",
          "marketType": "MC"
      },
      {
          "folio": 200023,
          "symbol": "TSLA",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 2.0,
          "canceledShares": 0.0,
          "price": 7945.30,
          "total": 15890.60,
          "sharesAssigned": 2.0,
          "status": "Asignada",
          "orderDate": "08/11/2024",
          "expirationDate": "08/11/2024",
          "orderTime": "10:20:15",
          "marketType": "SIC"
      },
      {
          "folio": 200024,
          "symbol": "ASURB",
          "series": "B",
          "orderType": "COMPRA",
          "shares": 25.0,
          "canceledShares": 0.0,
          "price": 620.50,
          "total": 15512.50,
          "sharesAssigned": 25.0,
          "status": "Asignada",
          "orderDate": "11/11/2024",
          "expirationDate": "11/11/2024",
          "orderTime": "09:40:25",
          "marketType": "MC"
      },
      {
          "folio": 200025,
          "symbol": "ASURB",
          "series": "B",
          "orderType": "VENTA",
          "shares": 25.0,
          "canceledShares": 0.0,
          "price": 635.75,
          "total": 15893.75,
          "sharesAssigned": 25.0,
          "status": "Asignada",
          "orderDate": "11/11/2024",
          "expirationDate": "11/11/2024",
          "orderTime": "13:25:40",
          "marketType": "MC"
      },
      {
          "folio": 200026,
          "symbol": "AAPL",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 3.0,
          "canceledShares": 0.0,
          "price": 4385.50,
          "total": 13156.50,
          "sharesAssigned": 3.0,
          "status": "Asignada",
          "orderDate": "12/11/2024",
          "expirationDate": "12/11/2024",
          "orderTime": "10:15:30",
          "marketType": "SIC"
      },
      {
          "folio": 200027,
          "symbol": "GMEXICOB",
          "series": "B",
          "orderType": "COMPRA",
          "shares": 120.0,
          "canceledShares": 0.0,
          "price": 128.45,
          "total": 15414.00,
          "sharesAssigned": 120.0,
          "status": "Asignada",
          "orderDate": "15/11/2024",
          "expirationDate": "15/11/2024",
          "orderTime": "09:20:45",
          "marketType": "MC"
      },
      {
          "folio": 200028,
          "symbol": "GMEXICOB",
          "series": "B",
          "orderType": "VENTA",
          "shares": 120.0,
          "canceledShares": 0.0,
          "price": 132.80,
          "total": 15936.00,
          "sharesAssigned": 120.0,
          "status": "Asignada",
          "orderDate": "15/11/2024",
          "expirationDate": "15/11/2024",
          "orderTime": "14:35:20",
          "marketType": "MC"
      },
      {
          "folio": 200029,
          "symbol": "ALFAA",
          "series": "A",
          "orderType": "COMPRA",
          "shares": 300.0,
          "canceledShares": 0.0,
          "price": 14.85,
          "total": 4455.00,
          "sharesAssigned": 300.0,
          "status": "Asignada",
          "orderDate": "18/11/2024",
          "expirationDate": "18/11/2024",
          "orderTime": "10:45:15",
          "marketType": "MC"
      },
      {
          "folio": 200030,
          "symbol": "ALFAA",
          "series": "A",
          "orderType": "VENTA",
          "shares": 300.0,
          "canceledShares": 0.0,
          "price": 14.60,
          "total": 4380.00,
          "sharesAssigned": 300.0,
          "status": "Asignada",
          "orderDate": "18/11/2024",
          "expirationDate": "18/11/2024",
          "orderTime": "15:20:35",
          "marketType": "MC"
      },
      {
          "folio": 200031,
          "symbol": "KOFUBL",
          "series": "UBL",
          "orderType": "COMPRA",
          "shares": 80.0,
          "canceledShares": 0.0,
          "price": 155.60,
          "total": 12448.00,
          "sharesAssigned": 80.0,
          "status": "Asignada",
          "orderDate": "22/11/2024",
          "expirationDate": "22/11/2024",
          "orderTime": "09:30:25",
          "marketType": "MC"
      },
      {
          "folio": 200032,
          "symbol": "KOFUBL",
          "series": "UBL",
          "orderType": "VENTA",
          "shares": 80.0,
          "canceledShares": 0.0,
          "price": 158.95,
          "total": 12716.00,
          "sharesAssigned": 80.0,
          "status": "Asignada",
          "orderDate": "22/11/2024",
          "expirationDate": "22/11/2024",
          "orderTime": "12:15:40",
          "marketType": "MC"
      },
      {
          "folio": 200033,
          "symbol": "META",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 2.0,
          "canceledShares": 0.0,
          "price": 5940.25,
          "total": 11880.50,
          "sharesAssigned": 2.0,
          "status": "Asignada",
          "orderDate": "25/11/2024",
          "expirationDate": "25/11/2024",
          "orderTime": "10:20:15",
          "marketType": "SIC"
      },
      {
          "folio": 200034,
          "symbol": "META",
          "series": "*",
          "orderType": "VENTA",
          "shares": 2.0,
          "canceledShares": 0.0,
          "price": 6185.70,
          "total": 12371.40,
          "sharesAssigned": 2.0,
          "status": "Asignada",
          "orderDate": "25/11/2024",
          "expirationDate": "25/11/2024",
          "orderTime": "13:45:50",
          "marketType": "SIC"
      },
      {
          "folio": 200035,
          "symbol": "MSFT",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 1.0,
          "canceledShares": 0.0,
          "price": 8850.75,
          "total": 8850.75,
          "sharesAssigned": 1.0,
          "status": "Asignada",
          "orderDate": "29/11/2024",
          "expirationDate": "29/11/2024",
          "orderTime": "09:35:30",
          "marketType": "SIC"
      },
      {
          "folio": 200036,
          "symbol": "TLEVISACPO",
          "series": "CPO",
          "orderType": "COMPRA",
          "shares": 500.0,
          "canceledShares": 0.0,
          "price": 24.50,
          "total": 12250.00,
          "sharesAssigned": 500.0,
          "status": "Asignada",
          "orderDate": "02/12/2024",
          "expirationDate": "02/12/2024",
          "orderTime": "10:15:45",
          "marketType": "MC"
      },
      {
          "folio": 200037,
          "symbol": "TLEVISACPO",
          "series": "CPO",
          "orderType": "VENTA",
          "shares": 500.0,
          "canceledShares": 0.0,
          "price": 23.85,
          "total": 11925.00,
          "sharesAssigned": 500.0,
          "status": "Asignada",
          "orderDate": "02/12/2024",
          "expirationDate": "02/12/2024",
          "orderTime": "14:50:20",
          "marketType": "MC"
      },
      {
          "folio": 200038,
          "symbol": "WALMEX",
          "series": "*",
          "orderType": "VENTA",
          "shares": 100.0,
          "canceledShares": 0.0,
          "price": 57.95,
          "total": 5795.00,
          "sharesAssigned": 100.0,
          "status": "Asignada",
          "orderDate": "06/12/2024",
          "expirationDate": "06/12/2024",
          "orderTime": "11:25:35",
          "marketType": "MC"
      },
      {
          "folio": 200039,
          "symbol": "ORBIA",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 200.0,
          "canceledShares": 0.0,
          "price": 32.80,
          "total": 6560.00,
          "sharesAssigned": 200.0,
          "status": "Asignada",
          "orderDate": "09/12/2024",
          "expirationDate": "09/12/2024",
          "orderTime": "09:40:25",
          "marketType": "MC"
      },
      {
          "folio": 200040,
          "symbol": "ORBIA",
          "series": "*",
          "orderType": "VENTA",
          "shares": 200.0,
          "canceledShares": 0.0,
          "price": 33.95,
          "total": 6790.00,
          "sharesAssigned": 200.0,
          "status": "Asignada",
          "orderDate": "09/12/2024",
          "expirationDate": "09/12/2024",
          "orderTime": "12:15:40",
          "marketType": "MC"
      },
      {
          "folio": 200041,
          "symbol": "GOOGL",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 3.0,
          "canceledShares": 0.0,
          "price": 3285.40,
          "total": 9856.20,
          "sharesAssigned": 3.0,
          "status": "Asignada",
          "orderDate": "13/12/2024",
          "expirationDate": "13/12/2024",
          "orderTime": "10:30:15",
          "marketType": "SIC"
      },
      {
          "folio": 200042,
          "symbol": "GOOGL",
          "series": "*",
          "orderType": "VENTA",
          "shares": 3.0,
          "canceledShares": 0.0,
          "price": 3420.85,
          "total": 10262.55,
          "sharesAssigned": 3.0,
          "status": "Asignada",
          "orderDate": "13/12/2024",
          "expirationDate": "13/12/2024",
          "orderTime": "15:20:30",
          "marketType": "SIC"
      },
      {
          "folio": 200043,
          "symbol": "GRUMAB",
          "series": "B",
          "orderType": "COMPRA",
          "shares": 60.0,
          "canceledShares": 0.0,
          "price": 248.50,
          "total": 14910.00,
          "sharesAssigned": 60.0,
          "status": "Asignada",
          "orderDate": "16/12/2024",
          "expirationDate": "16/12/2024",
          "orderTime": "09:25:45",
          "marketType": "MC"
      },
      {
          "folio": 200044,
          "symbol": "GRUMAB",
          "series": "B",
          "orderType": "VENTA",
          "shares": 60.0,
          "canceledShares": 0.0,
          "price": 245.20,
          "total": 14712.00,
          "sharesAssigned": 60.0,
          "status": "Asignada",
          "orderDate": "16/12/2024",
          "expirationDate": "16/12/2024",
          "orderTime": "13:40:20",
          "marketType": "MC"
      },
      {
          "folio": 200045,
          "symbol": "LIVEPOLC1",
          "series": "C-1",
          "orderType": "COMPRA",
          "shares": 150.0,
          "canceledShares": 0.0,
          "price": 42.80,
          "total": 6420.00,
          "sharesAssigned": 150.0,
          "status": "Asignada",
          "orderDate": "20/12/2024",
          "expirationDate": "20/12/2024",
          "orderTime": "10:45:30",
          "marketType": "MC"
      },
      {
          "folio": 200046,
          "symbol": "LIVEPOLC1",
          "series": "C-1",
          "orderType": "VENTA",
          "shares": 150.0,
          "canceledShares": 0.0,
          "price": 41.95,
          "total": 6292.50,
          "sharesAssigned": 150.0,
          "status": "Asignada",
          "orderDate": "20/12/2024",
          "expirationDate": "20/12/2024",
          "orderTime": "14:25:15",
          "marketType": "MC"
      },
      {
          "folio": 200047,
          "symbol": "AMZN",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 4.0,
          "canceledShares": 0.0,
          "price": 3840.60,
          "total": 15362.40,
          "sharesAssigned": 4.0,
          "status": "Asignada",
          "orderDate": "08/01/2025",
          "expirationDate": "08/01/2025",
          "orderTime": "09:30:20",
          "marketType": "SIC"
      },
      {
          "folio": 200048,
          "symbol": "AMZN",
          "series": "*",
          "orderType": "VENTA",
          "shares": 4.0,
          "canceledShares": 0.0,
          "price": 3920.15,
          "total": 15680.60,
          "sharesAssigned": 4.0,
          "status": "Asignada",
          "orderDate": "08/01/2025",
          "expirationDate": "08/01/2025",
          "orderTime": "11:45:35",
          "marketType": "SIC"
      },
      {
          "folio": 200049,
          "symbol": "ELEKTRA",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 10.0,
          "canceledShares": 0.0,
          "price": 980.50,
          "total": 9805.00,
          "sharesAssigned": 10.0,
          "status": "Asignada",
          "orderDate": "15/01/2025",
          "expirationDate": "15/01/2025",
          "orderTime": "10:20:45",
          "marketType": "MC"
      },
      {
          "folio": 200050,
          "symbol": "ELEKTRA",
          "series": "*",
          "orderType": "VENTA",
          "shares": 10.0,
          "canceledShares": 0.0,
          "price": 965.75,
          "total": 9657.50,
          "sharesAssigned": 10.0,
          "status": "Asignada",
          "orderDate": "15/01/2025",
          "expirationDate": "15/01/2025",
          "orderTime": "13:50:20",
          "marketType": "MC"
      },
      {
          "folio": 200051,
          "symbol": "PE&OLES",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 20.0,
          "canceledShares": 0.0,
          "price": 740.80,
          "total": 14816.00,
          "sharesAssigned": 20.0,
          "status": "Asignada",
          "orderDate": "22/01/2025",
          "expirationDate": "22/01/2025",
          "orderTime": "09:35:15",
          "marketType": "MC"
      },
      {
          "folio": 200052,
          "symbol": "PE&OLES",
          "series": "*",
          "orderType": "VENTA",
          "shares": 20.0,
          "canceledShares": 0.0,
          "price": 758.20,
          "total": 15164.00,
          "sharesAssigned": 20.0,
          "status": "Asignada",
          "orderDate": "22/01/2025",
          "expirationDate": "22/01/2025",
          "orderTime": "12:25:40",
          "marketType": "MC"
      },
      {
          "folio": 200053,
          "symbol": "NFLX",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 2.0,
          "canceledShares": 0.0,
          "price": 12450.30,
          "total": 24900.60,
          "sharesAssigned": 2.0,
          "status": "Asignada",
          "orderDate": "29/01/2025",
          "expirationDate": "29/01/2025",
          "orderTime": "10:15:25",
          "marketType": "SIC"
      },
      {
          "folio": 200054,
          "symbol": "NFLX",
          "series": "*",
          "orderType": "VENTA",
          "shares": 2.0,
          "canceledShares": 0.0,
          "price": 12680.75,
          "total": 25361.50,
          "sharesAssigned": 2.0,
          "status": "Asignada",
          "orderDate": "29/01/2025",
          "expirationDate": "29/01/2025",
          "orderTime": "14:40:30",
          "marketType": "SIC"
      },
      {
          "folio": 200055,
          "symbol": "IENOVA",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 250.0,
          "canceledShares": 0.0,
          "price": 98.50,
          "total": 24625.00,
          "sharesAssigned": 250.0,
          "status": "Asignada",
          "orderDate": "05/02/2025",
          "expirationDate": "05/02/2025",
          "orderTime": "09:45:20",
          "marketType": "MC"
      },
      {
          "folio": 200056,
          "symbol": "IENOVA",
          "series": "*",
          "orderType": "VENTA",
          "shares": 250.0,
          "canceledShares": 0.0,
          "price": 96.85,
          "total": 24212.50,
          "sharesAssigned": 250.0,
          "status": "Asignada",
          "orderDate": "05/02/2025",
          "expirationDate": "05/02/2025",
          "orderTime": "13:20:45",
          "marketType": "MC"
      },
      {
          "folio": 200057,
          "symbol": "CUERVO",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 180.0,
          "canceledShares": 0.0,
          "price": 85.40,
          "total": 15372.00,
          "sharesAssigned": 180.0,
          "status": "Asignada",
          "orderDate": "12/02/2025",
          "expirationDate": "12/02/2025",
          "orderTime": "10:30:35",
          "marketType": "MC"
      },
      {
          "folio": 200058,
          "symbol": "CUERVO",
          "series": "*",
          "orderType": "VENTA",
          "shares": 180.0,
          "canceledShares": 0.0,
          "price": 87.95,
          "total": 15831.00,
          "sharesAssigned": 180.0,
          "status": "Asignada",
          "orderDate": "12/02/2025",
          "expirationDate": "12/02/2025",
          "orderTime": "15:15:20",
          "marketType": "MC"
      },
      {
          "folio": 200059,
          "symbol": "UBER",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 15.0,
          "canceledShares": 0.0,
          "price": 1280.40,
          "total": 19206.00,
          "sharesAssigned": 15.0,
          "status": "Asignada",
          "orderDate": "19/02/2025",
          "expirationDate": "19/02/2025",
          "orderTime": "09:25:15",
          "marketType": "SIC"
      },
      {
          "folio": 200060,
          "symbol": "UBER",
          "series": "*",
          "orderType": "VENTA",
          "shares": 15.0,
          "canceledShares": 0.0,
          "price": 1295.80,
          "total": 19437.00,
          "sharesAssigned": 15.0,
          "status": "Asignada",
          "orderDate": "19/02/2025",
          "expirationDate": "19/02/2025",
          "orderTime": "11:50:40",
          "marketType": "SIC"
      },
      {
          "folio": 577635,
          "symbol": "",
          "series": "",
          "orderType": "Cgo. Com.Admon.Cust",
          "shares": 0.0,
          "canceledShares": 0.0,
          "price": 0.0,
          "total": 0.41,
          "sharesAssigned": 0.0,
          "status": "Asignada",
          "orderDate": "26/02/2025",
          "expirationDate": "28/02/2025",
          "orderTime": "16:04:38",
          "marketType": "CJ"
      },
      {
          "folio": 853206,
          "symbol": "",
          "series": "",
          "orderType": "Cgo. Com.Admon.Cust",
          "shares": 0.0,
          "canceledShares": 0.0,
          "price": 0.0,
          "total": 0.41,
          "sharesAssigned": 0.0,
          "status": "Asignada",
          "orderDate": "31/03/2025",
          "expirationDate": "31/03/2025",
          "orderTime": "16:04:05",
          "marketType": "CJ"
      }
  ];
    
    // Calculate summary statistics for DT
    const totalTrades = trades.length;
    const buyTrades = trades.filter(trade =>
      trade.orderType === 'COMPRA' ||
      trade.orderType === 'COMPRA ADICIONAL'
    );
    const sellTrades = trades.filter(trade =>
      trade.orderType === 'VENTA PARCIAL' ||
      trade.orderType === 'VENTA'
    );
    const totalBuyValue = buyTrades.reduce((sum, trade) => sum + trade.total, 0);
    const totalSellValue = sellTrades.reduce((sum, trade) => sum + trade.total, 0);
    const commissionTrades = trades.filter(trade =>
      trade.orderType === 'Cgo. Com.Admon.Cust'
    );
    const totalCommission = commissionTrades.reduce((sum, trade) => sum + trade.total, 0);
    const netCashFlow = totalBuyValue - totalSellValue - totalCommission;

    return {
      data: trades,
      summary: {
        totalTrades,
        totalBuyValue,
        totalSellValue,
        totalCommission,
        netCashFlow,
      }
    };
  } else {
    // Long Term trade history data (LT)
    const trades = [
      {
          "folio": 987654,
          "symbol": "WALMEX",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 150.0,
          "canceledShares": 0.0,
          "price": 58.99,
          "total": 8848.5,
          "sharesAssigned": 150.0,
          "status": "Asignada",
          "orderDate": "16/10/2024",
          "expirationDate": "16/10/2024",
          "orderTime": "10:15:30",
          "marketType": "MC"
      },
      {
          "folio": 987655,
          "symbol": "FEMSAUBD",
          "series": "UBD",
          "orderType": "COMPRA",
          "shares": 40.0,
          "canceledShares": 0.0,
          "price": 193.97,
          "total": 7758.8,
          "sharesAssigned": 40.0,
          "status": "Asignada",
          "orderDate": "16/10/2024",
          "expirationDate": "16/10/2024",
          "orderTime": "10:22:15",
          "marketType": "MC"
      },
      {
          "folio": 987656,
          "symbol": "AMXB",
          "series": "B",
          "orderType": "COMPRA",
          "shares": 350.0,
          "canceledShares": 0.0,
          "price": 15.31,
          "total": 5358.5,
          "sharesAssigned": 350.0,
          "status": "Asignada",
          "orderDate": "16/10/2024",
          "expirationDate": "16/10/2024",
          "orderTime": "10:35:45",
          "marketType": "MC"
      },
      {
          "folio": 987657,
          "symbol": "CEMEXCPO",
          "series": "CPO",
          "orderType": "COMPRA",
          "shares": 500.0,
          "canceledShares": 0.0,
          "price": 11.81,
          "total": 5905.0,
          "sharesAssigned": 500.0,
          "status": "Asignada",
          "orderDate": "16/10/2024",
          "expirationDate": "16/10/2024",
          "orderTime": "11:10:20",
          "marketType": "MC"
      },
      {
          "folio": 987658,
          "symbol": "GAPB",
          "series": "B",
          "orderType": "COMPRA",
          "shares": 15.0,
          "canceledShares": 0.0,
          "price": 344.32,
          "total": 5164.8,
          "sharesAssigned": 15.0,
          "status": "Asignada",
          "orderDate": "16/10/2024",
          "expirationDate": "16/10/2024",
          "orderTime": "11:45:10",
          "marketType": "MC"
      },
      {
          "folio": 987659,
          "symbol": "GFNORTEO",
          "series": "O",
          "orderType": "COMPRA",
          "shares": 35.0,
          "canceledShares": 0.0,
          "price": 144.83,
          "total": 5069.05,
          "sharesAssigned": 35.0,
          "status": "Asignada",
          "orderDate": "16/10/2024",
          "expirationDate": "16/10/2024",
          "orderTime": "14:20:35",
          "marketType": "MC"
      },
      {
          "folio": 987660,
          "symbol": "BIMBOA",
          "series": "A",
          "orderType": "COMPRA",
          "shares": 100.0,
          "canceledShares": 0.0,
          "price": 65.09,
          "total": 6509.0,
          "sharesAssigned": 100.0,
          "status": "Asignada",
          "orderDate": "16/10/2024",
          "expirationDate": "16/10/2024",
          "orderTime": "14:55:25",
          "marketType": "MC"
      },
      {
          "folio": 987661,
          "symbol": "AAPL",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 2.0,
          "canceledShares": 0.0,
          "price": 4410.8,
          "total": 8821.6,
          "sharesAssigned": 2.0,
          "status": "Asignada",
          "orderDate": "16/10/2024",
          "expirationDate": "16/10/2024",
          "orderTime": "09:30:15",
          "marketType": "SIC"
      },
      {
          "folio": 987662,
          "symbol": "TSLA",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 2.0,
          "canceledShares": 0.0,
          "price": 8281.67,
          "total": 16563.34,
          "sharesAssigned": 2.0,
          "status": "Asignada",
          "orderDate": "16/10/2024",
          "expirationDate": "16/10/2024",
          "orderTime": "10:15:40",
          "marketType": "SIC"
      },
      {
          "folio": 987663,
          "symbol": "MSFT",
          "series": "*",
          "orderType": "COMPRA",
          "shares": 1.0,
          "canceledShares": 0.0,
          "price": 8281.67,
          "total": 8281.67,
          "sharesAssigned": 1.0,
          "status": "Asignada",
          "orderDate": "16/10/2024",
          "expirationDate": "16/10/2024",
          "orderTime": "11:30:55",
          "marketType": "SIC"
      },
      {
          "folio": 577635,
          "symbol": "",
          "series": "",
          "orderType": "Cgo. Com.Admon.Cust",
          "shares": 0.0,
          "canceledShares": 0.0,
          "price": 0.0,
          "total": 0.41,
          "sharesAssigned": 0.0,
          "status": "Asignada",
          "orderDate": "26/10/2024",
          "expirationDate": "30/10/2024",
          "orderTime": "16:04:38",
          "marketType": "CJ"
      },
      {
          "folio": 853206,
          "symbol": "",
          "series": "",
          "orderType": "Cgo. Com.Admon.Cust",
          "shares": 0.0,
          "canceledShares": 0.0,
          "price": 0.0,
          "total": 0.41,
          "sharesAssigned": 0.0,
          "status": "Asignada",
          "orderDate": "29/11/2024",
          "expirationDate": "30/11/2024",
          "orderTime": "16:04:05",
          "marketType": "CJ"
      }
  ];

    // Calculate summary statistics for LT
    const totalTrades = trades.length;
    
    // Calculate buy and sell values based on orderType
    const buyTrades = trades.filter(trade => 
      trade.orderType === 'COMPRA' || 
      trade.orderType === 'COMPRA ADICIONAL'
    );
    const sellTrades = trades.filter(trade => 
      trade.orderType === 'VENTA PARCIAL' || 
      trade.orderType === 'VENTA'
    );
    
    const totalBuyValue = buyTrades.reduce((sum, trade) => sum + (trade.total || 0), 0);
    const totalSellValue = sellTrades.reduce((sum, trade) => sum + (trade.total || 0), 0);
    
    // Calculate commission from administrative charges
    const commissionTrades = trades.filter(trade => 
      trade.orderType === 'Cgo. Com.Admon.Cust'
    );
    const totalCommission = commissionTrades.reduce((sum, trade) => sum + (trade.total || 0), 0);
    
    // Calculate net cash flow (buy - sell - commission)
    const netCashFlow = totalBuyValue - totalSellValue - totalCommission;

    return {
      data: trades,
      summary: {
        totalTrades,
        totalBuyValue,
        totalSellValue,
        totalCommission,
        netCashFlow,
      }
    };
  }
};
